// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-core/src/main/java/com/winmanboo/space/im/server/core/codec/protocol/pack/ack/confirm_ack.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.core.codec.protocol.pack.ack;

public interface ConfirmAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.winmanboo.space.im.core.codec.protocol.pack.ack.ConfirmAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ack = 1;</code>
   * @return The ack.
   */
  int getAck();

  /**
   * <pre>
   * 消息 id（唯一）
   * </pre>
   *
   * <code>string messageId = 2;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <pre>
   * 消息 id（唯一）
   * </pre>
   *
   * <code>string messageId = 2;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <pre>
   * 状态标志，0-失败,1-成功
   * </pre>
   *
   * <code>int32 resultCode = 3;</code>
   * @return The resultCode.
   */
  int getResultCode();

  /**
   * <code>.com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack data = 4;</code>
   * @return The data.
   */
  com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack getData();
  /**
   * <code>.com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack data = 4;</code>
   */
  com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePackOrBuilder getDataOrBuilder();
}
