// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-core/src/main/java/com/winmanboo/space/im/server/core/codec/protocol/pack/ack/confirm_ack.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.core.codec.protocol.pack.ack;

public interface MessagePackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string toId = 2;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>string toId = 2;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>string msgId = 3;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <code>string msgId = 3;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>int32 msgType = 4;</code>
   * @return The msgType.
   */
  int getMsgType();

  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
