// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-core/src/main/java/com/winmanboo/space/im/server/core/codec/protocol/pack/ack/confirm_ack.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.core.codec.protocol.pack.ack;

/**
 * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack}
 */
public final class MessagePack extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack)
    MessagePackOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      MessagePack.class.getName());
  }
  // Use MessagePack.newBuilder() to construct.
  private MessagePack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MessagePack() {
    userId_ = "";
    toId_ = "";
    msgId_ = "";
    data_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.ConfirmAckProto.internal_static_com_winmanboo_space_im_core_codec_protocol_pack_ack_MessagePack_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.ConfirmAckProto.internal_static_com_winmanboo_space_im_core_codec_protocol_pack_ack_MessagePack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.class, com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toId_ = "";
  /**
   * <code>string toId = 2;</code>
   * @return The toId.
   */
  @java.lang.Override
  public java.lang.String getToId() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toId_ = s;
      return s;
    }
  }
  /**
   * <code>string toId = 2;</code>
   * @return The bytes for toId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToIdBytes() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgId_ = "";
  /**
   * <code>string msgId = 3;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public java.lang.String getMsgId() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <code>string msgId = 3;</code>
   * @return The bytes for msgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGTYPE_FIELD_NUMBER = 4;
  private int msgType_ = 0;
  /**
   * <code>int32 msgType = 4;</code>
   * @return The msgType.
   */
  @java.lang.Override
  public int getMsgType() {
    return msgType_;
  }

  public static final int DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object data_ = "";
  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, toId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, msgId_);
    }
    if (msgType_ != 0) {
      output.writeInt32(4, msgType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, toId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, msgId_);
    }
    if (msgType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, msgType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack)) {
      return super.equals(obj);
    }
    com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack other = (com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getToId()
        .equals(other.getToId())) return false;
    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (getMsgType()
        != other.getMsgType()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + TOID_FIELD_NUMBER;
    hash = (53 * hash) + getToId().hashCode();
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgType();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack)
      com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.ConfirmAckProto.internal_static_com_winmanboo_space_im_core_codec_protocol_pack_ack_MessagePack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.ConfirmAckProto.internal_static_com_winmanboo_space_im_core_codec_protocol_pack_ack_MessagePack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.class, com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.Builder.class);
    }

    // Construct using com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      toId_ = "";
      msgId_ = "";
      msgType_ = 0;
      data_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.ConfirmAckProto.internal_static_com_winmanboo_space_im_core_codec_protocol_pack_ack_MessagePack_descriptor;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack getDefaultInstanceForType() {
      return com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.getDefaultInstance();
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack build() {
      com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack buildPartial() {
      com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack result = new com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toId_ = toId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.msgType_ = msgType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.data_ = data_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack) {
        return mergeFrom((com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack other) {
      if (other == com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getToId().isEmpty()) {
        toId_ = other.toId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getMsgType() != 0) {
        setMsgType(other.getMsgType());
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              toId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              msgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              msgType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object toId_ = "";
    /**
     * <code>string toId = 2;</code>
     * @return The toId.
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string toId = 2;</code>
     * @return The bytes for toId.
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string toId = 2;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string toId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      toId_ = getDefaultInstance().getToId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string toId = 2;</code>
     * @param value The bytes for toId to set.
     * @return This builder for chaining.
     */
    public Builder setToIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object msgId_ = "";
    /**
     * <code>string msgId = 3;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgId = 3;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgId = 3;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string msgId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      msgId_ = getDefaultInstance().getMsgId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string msgId = 3;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int msgType_ ;
    /**
     * <code>int32 msgType = 4;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public int getMsgType() {
      return msgType_;
    }
    /**
     * <code>int32 msgType = 4;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(int value) {

      msgType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msgType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack)
  }

  // @@protoc_insertion_point(class_scope:com.winmanboo.space.im.core.codec.protocol.pack.ack.MessagePack)
  private static final com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack();
  }

  public static com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessagePack>
      PARSER = new com.google.protobuf.AbstractParser<MessagePack>() {
    @java.lang.Override
    public MessagePack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessagePack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessagePack> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.winmanboo.space.im.server.core.codec.protocol.pack.ack.MessagePack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

