#spring:
#  application:
#    name: im-data-core
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: db_message
#    redis:
#      host: localhost
#      port: 6379
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 50
#          max-idle: 20
#      password: wzm123
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://localhost:8848
#    username: nacos
#    password: nacos
#  protocol:
#    name: dubbo
#    port: 9101
#
#space:
#  mq:
#    name-server: localhost:9876
#    producer:
#      enable: true
#      group: ${spring.application.name}
#      send-msg-timeout: 3000
#      retry-times-when-send-failed: 2
#      retry-times-when-send-async-failed: 2
#      retry-another-broker-when-not-store-ok: true
#    consumer:
#      enable: true
#      group: ${spring.application.name}
#      consume-message-batch-max-size: 10
#      consume-from-where: consume_from_first_offset