// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-api/src/main/java/com/winmanboo/space/im/server/api/protocol/message/message.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.api.protocol.message;

/**
 * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.Body}
 */
public final class Body extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.winmanboo.space.im.core.codec.protocol.Body)
    BodyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Body.class.getName());
  }
  // Use Body.newBuilder() to construct.
  private Body(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Body() {
    userId_ = "";
    toId_ = "";
    msgId_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Body_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.winmanboo.space.im.server.api.protocol.message.Body.class, com.winmanboo.space.im.server.api.protocol.message.Body.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * 发送方 id
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送方 id
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPID_FIELD_NUMBER = 2;
  private int appId_ = 0;
  /**
   * <pre>
   * 业务 id
   * </pre>
   *
   * <code>int32 appId = 2;</code>
   * @return The appId.
   */
  @java.lang.Override
  public int getAppId() {
    return appId_;
  }

  public static final int TOID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toId_ = "";
  /**
   * <pre>
   * 接收方 id
   * </pre>
   *
   * <code>string toId = 3;</code>
   * @return The toId.
   */
  @java.lang.Override
  public java.lang.String getToId() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接收方 id
   * </pre>
   *
   * <code>string toId = 3;</code>
   * @return The bytes for toId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToIdBytes() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgId_ = "";
  /**
   * <pre>
   * 消息 id，一般不由客户端传递
   * </pre>
   *
   * <code>string msgId = 4;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public java.lang.String getMsgId() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息 id，一般不由客户端传递
   * </pre>
   *
   * <code>string msgId = 4;</code>
   * @return The bytes for msgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CMDID_FIELD_NUMBER = 5;
  private int cmdId_ = 0;
  /**
   * <pre>
   * 业务指令 id
   * </pre>
   *
   * <code>int32 cmdId = 5;</code>
   * @return The cmdId.
   */
  @java.lang.Override
  public int getCmdId() {
    return cmdId_;
  }

  public static final int MSGTYPE_FIELD_NUMBER = 6;
  private int msgType_ = 0;
  /**
   * <pre>
   * 消息类型，例如普通文字消息、语音消息以及文件
   * </pre>
   *
   * <code>int32 msgType = 6;</code>
   * @return The msgType.
   */
  @java.lang.Override
  public int getMsgType() {
    return msgType_;
  }

  public static final int DATA_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 消息包内容
   * </pre>
   *
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
    }
    if (appId_ != 0) {
      output.writeInt32(2, appId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, toId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, msgId_);
    }
    if (cmdId_ != 0) {
      output.writeInt32(5, cmdId_);
    }
    if (msgType_ != 0) {
      output.writeInt32(6, msgType_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(7, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
    }
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, appId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, toId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, msgId_);
    }
    if (cmdId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, cmdId_);
    }
    if (msgType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, msgType_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.winmanboo.space.im.server.api.protocol.message.Body)) {
      return super.equals(obj);
    }
    com.winmanboo.space.im.server.api.protocol.message.Body other = (com.winmanboo.space.im.server.api.protocol.message.Body) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (getAppId()
        != other.getAppId()) return false;
    if (!getToId()
        .equals(other.getToId())) return false;
    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (getCmdId()
        != other.getCmdId()) return false;
    if (getMsgType()
        != other.getMsgType()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + TOID_FIELD_NUMBER;
    hash = (53 * hash) + getToId().hashCode();
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (37 * hash) + CMDID_FIELD_NUMBER;
    hash = (53 * hash) + getCmdId();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgType();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Body parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Body parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Body parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.winmanboo.space.im.server.api.protocol.message.Body prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.Body}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.winmanboo.space.im.core.codec.protocol.Body)
      com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winmanboo.space.im.server.api.protocol.message.Body.class, com.winmanboo.space.im.server.api.protocol.message.Body.Builder.class);
    }

    // Construct using com.winmanboo.space.im.server.api.protocol.message.Body.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      appId_ = 0;
      toId_ = "";
      msgId_ = "";
      cmdId_ = 0;
      msgType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Body getDefaultInstanceForType() {
      return com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance();
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Body build() {
      com.winmanboo.space.im.server.api.protocol.message.Body result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Body buildPartial() {
      com.winmanboo.space.im.server.api.protocol.message.Body result = new com.winmanboo.space.im.server.api.protocol.message.Body(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.winmanboo.space.im.server.api.protocol.message.Body result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.appId_ = appId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.toId_ = toId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.cmdId_ = cmdId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.msgType_ = msgType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.data_ = data_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.winmanboo.space.im.server.api.protocol.message.Body) {
        return mergeFrom((com.winmanboo.space.im.server.api.protocol.message.Body)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.winmanboo.space.im.server.api.protocol.message.Body other) {
      if (other == com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (!other.getToId().isEmpty()) {
        toId_ = other.toId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getCmdId() != 0) {
        setCmdId(other.getCmdId());
      }
      if (other.getMsgType() != 0) {
        setMsgType(other.getMsgType());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              appId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              toId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              msgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              cmdId_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              msgType_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              data_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * 发送方 id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送方 id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送方 id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送方 id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送方 id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int appId_ ;
    /**
     * <pre>
     * 业务 id
     * </pre>
     *
     * <code>int32 appId = 2;</code>
     * @return The appId.
     */
    @java.lang.Override
    public int getAppId() {
      return appId_;
    }
    /**
     * <pre>
     * 业务 id
     * </pre>
     *
     * <code>int32 appId = 2;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(int value) {

      appId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务 id
     * </pre>
     *
     * <code>int32 appId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      appId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object toId_ = "";
    /**
     * <pre>
     * 接收方 id
     * </pre>
     *
     * <code>string toId = 3;</code>
     * @return The toId.
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 接收方 id
     * </pre>
     *
     * <code>string toId = 3;</code>
     * @return The bytes for toId.
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接收方 id
     * </pre>
     *
     * <code>string toId = 3;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收方 id
     * </pre>
     *
     * <code>string toId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      toId_ = getDefaultInstance().getToId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收方 id
     * </pre>
     *
     * <code>string toId = 3;</code>
     * @param value The bytes for toId to set.
     * @return This builder for chaining.
     */
    public Builder setToIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object msgId_ = "";
    /**
     * <pre>
     * 消息 id，一般不由客户端传递
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息 id，一般不由客户端传递
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息 id，一般不由客户端传递
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息 id，一般不由客户端传递
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      msgId_ = getDefaultInstance().getMsgId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息 id，一般不由客户端传递
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int cmdId_ ;
    /**
     * <pre>
     * 业务指令 id
     * </pre>
     *
     * <code>int32 cmdId = 5;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }
    /**
     * <pre>
     * 业务指令 id
     * </pre>
     *
     * <code>int32 cmdId = 5;</code>
     * @param value The cmdId to set.
     * @return This builder for chaining.
     */
    public Builder setCmdId(int value) {

      cmdId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务指令 id
     * </pre>
     *
     * <code>int32 cmdId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmdId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      cmdId_ = 0;
      onChanged();
      return this;
    }

    private int msgType_ ;
    /**
     * <pre>
     * 消息类型，例如普通文字消息、语音消息以及文件
     * </pre>
     *
     * <code>int32 msgType = 6;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public int getMsgType() {
      return msgType_;
    }
    /**
     * <pre>
     * 消息类型，例如普通文字消息、语音消息以及文件
     * </pre>
     *
     * <code>int32 msgType = 6;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(int value) {

      msgType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型，例如普通文字消息、语音消息以及文件
     * </pre>
     *
     * <code>int32 msgType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息包内容
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     * 消息包内容
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息包内容
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000040);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.winmanboo.space.im.core.codec.protocol.Body)
  }

  // @@protoc_insertion_point(class_scope:com.winmanboo.space.im.core.codec.protocol.Body)
  private static final com.winmanboo.space.im.server.api.protocol.message.Body DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.winmanboo.space.im.server.api.protocol.message.Body();
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Body getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Body>
      PARSER = new com.google.protobuf.AbstractParser<Body>() {
    @java.lang.Override
    public Body parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Body> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Body> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.Body getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

