// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-api/src/main/java/com/winmanboo/space/im/server/api/protocol/message/message.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.api.protocol.message;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.winmanboo.space.im.core.codec.protocol.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 发送方 id
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 发送方 id
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 业务 id
   * </pre>
   *
   * <code>int32 appId = 2;</code>
   * @return The appId.
   */
  int getAppId();

  /**
   * <pre>
   * 接收方 id
   * </pre>
   *
   * <code>string toId = 3;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <pre>
   * 接收方 id
   * </pre>
   *
   * <code>string toId = 3;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <pre>
   * 消息 id，一般不由客户端传递
   * </pre>
   *
   * <code>string msgId = 4;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <pre>
   * 消息 id，一般不由客户端传递
   * </pre>
   *
   * <code>string msgId = 4;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   * 业务指令 id
   * </pre>
   *
   * <code>int32 cmdId = 5;</code>
   * @return The cmdId.
   */
  int getCmdId();

  /**
   * <pre>
   * 消息类型，例如普通文字消息、语音消息以及文件
   * </pre>
   *
   * <code>int32 msgType = 6;</code>
   * @return The msgType.
   */
  int getMsgType();

  /**
   * <pre>
   * 消息包内容
   * </pre>
   *
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
