// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-api/src/main/java/com/winmanboo/space/im/server/api/protocol/message/message.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.api.protocol.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.winmanboo.space.im.core.codec.protocol.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   * @return The header.
   */
  com.winmanboo.space.im.server.api.protocol.message.Header getHeader();
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   */
  com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   * @return The body.
   */
  com.winmanboo.space.im.server.api.protocol.message.Body getBody();
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   */
  com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder getBodyOrBuilder();
}
