// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-api/src/main/java/com/winmanboo/space/im/server/api/protocol/message/message.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.api.protocol.message;

/**
 * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.winmanboo.space.im.core.codec.protocol.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Message.class.getName());
  }
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.winmanboo.space.im.server.api.protocol.message.Message.class, com.winmanboo.space.im.server.api.protocol.message.Message.Builder.class);
  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.winmanboo.space.im.server.api.protocol.message.Header header_;
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.Header getHeader() {
    return header_ == null ? com.winmanboo.space.im.server.api.protocol.message.Header.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
   */
  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null ? com.winmanboo.space.im.server.api.protocol.message.Header.getDefaultInstance() : header_;
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private com.winmanboo.space.im.server.api.protocol.message.Body body_;
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   * @return Whether the body field is set.
   */
  @java.lang.Override
  public boolean hasBody() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.Body getBody() {
    return body_ == null ? com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance() : body_;
  }
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
   */
  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder getBodyOrBuilder() {
    return body_ == null ? com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance() : body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHeader());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBody());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBody());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.winmanboo.space.im.server.api.protocol.message.Message)) {
      return super.equals(obj);
    }
    com.winmanboo.space.im.server.api.protocol.message.Message other = (com.winmanboo.space.im.server.api.protocol.message.Message) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.winmanboo.space.im.server.api.protocol.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.winmanboo.space.im.server.api.protocol.message.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.winmanboo.space.im.core.codec.protocol.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.winmanboo.space.im.core.codec.protocol.Message)
      com.winmanboo.space.im.server.api.protocol.message.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winmanboo.space.im.server.api.protocol.message.Message.class, com.winmanboo.space.im.server.api.protocol.message.Message.Builder.class);
    }

    // Construct using com.winmanboo.space.im.server.api.protocol.message.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getHeaderFieldBuilder();
        getBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.winmanboo.space.im.server.api.protocol.message.MessageProto.internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Message getDefaultInstanceForType() {
      return com.winmanboo.space.im.server.api.protocol.message.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Message build() {
      com.winmanboo.space.im.server.api.protocol.message.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.winmanboo.space.im.server.api.protocol.message.Message buildPartial() {
      com.winmanboo.space.im.server.api.protocol.message.Message result = new com.winmanboo.space.im.server.api.protocol.message.Message(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.winmanboo.space.im.server.api.protocol.message.Message result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null
            ? header_
            : headerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.body_ = bodyBuilder_ == null
            ? body_
            : bodyBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.winmanboo.space.im.server.api.protocol.message.Message) {
        return mergeFrom((com.winmanboo.space.im.server.api.protocol.message.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.winmanboo.space.im.server.api.protocol.message.Message other) {
      if (other == com.winmanboo.space.im.server.api.protocol.message.Message.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.winmanboo.space.im.server.api.protocol.message.Header header_;
    private com.google.protobuf.SingleFieldBuilder<
        com.winmanboo.space.im.server.api.protocol.message.Header, com.winmanboo.space.im.server.api.protocol.message.Header.Builder, com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     * @return The header.
     */
    public com.winmanboo.space.im.server.api.protocol.message.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.winmanboo.space.im.server.api.protocol.message.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public Builder setHeader(com.winmanboo.space.im.server.api.protocol.message.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public Builder setHeader(
        com.winmanboo.space.im.server.api.protocol.message.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public Builder mergeHeader(com.winmanboo.space.im.server.api.protocol.message.Header value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          header_ != null &&
          header_ != com.winmanboo.space.im.server.api.protocol.message.Header.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      if (header_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public com.winmanboo.space.im.server.api.protocol.message.Header.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    public com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.winmanboo.space.im.server.api.protocol.message.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.winmanboo.space.im.server.api.protocol.message.Header, com.winmanboo.space.im.server.api.protocol.message.Header.Builder, com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.winmanboo.space.im.server.api.protocol.message.Header, com.winmanboo.space.im.server.api.protocol.message.Header.Builder, com.winmanboo.space.im.server.api.protocol.message.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.winmanboo.space.im.server.api.protocol.message.Body body_;
    private com.google.protobuf.SingleFieldBuilder<
        com.winmanboo.space.im.server.api.protocol.message.Body, com.winmanboo.space.im.server.api.protocol.message.Body.Builder, com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder> bodyBuilder_;
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     * @return The body.
     */
    public com.winmanboo.space.im.server.api.protocol.message.Body getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public Builder setBody(com.winmanboo.space.im.server.api.protocol.message.Body value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
      } else {
        bodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public Builder setBody(
        com.winmanboo.space.im.server.api.protocol.message.Body.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public Builder mergeBody(com.winmanboo.space.im.server.api.protocol.message.Body value) {
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          body_ != null &&
          body_ != com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance()) {
          getBodyBuilder().mergeFrom(value);
        } else {
          body_ = value;
        }
      } else {
        bodyBuilder_.mergeFrom(value);
      }
      if (body_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00000002);
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public com.winmanboo.space.im.server.api.protocol.message.Body.Builder getBodyBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    public com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.winmanboo.space.im.server.api.protocol.message.Body.getDefaultInstance() : body_;
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>.com.winmanboo.space.im.core.codec.protocol.Body body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.winmanboo.space.im.server.api.protocol.message.Body, com.winmanboo.space.im.server.api.protocol.message.Body.Builder, com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.winmanboo.space.im.server.api.protocol.message.Body, com.winmanboo.space.im.server.api.protocol.message.Body.Builder, com.winmanboo.space.im.server.api.protocol.message.BodyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.winmanboo.space.im.core.codec.protocol.Message)
  }

  // @@protoc_insertion_point(class_scope:com.winmanboo.space.im.core.codec.protocol.Message)
  private static final com.winmanboo.space.im.server.api.protocol.message.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.winmanboo.space.im.server.api.protocol.message.Message();
  }

  public static com.winmanboo.space.im.server.api.protocol.message.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.winmanboo.space.im.server.api.protocol.message.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

