// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im-server/im-server-api/src/main/java/com/winmanboo/space/im/server/api/protocol/message/message.proto
// Protobuf Java Version: 4.27.1

package com.winmanboo.space.im.server.api.protocol.message;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_winmanboo_space_im_core_codec_protocol_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_winmanboo_space_im_core_codec_protocol_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_winmanboo_space_im_core_codec_protocol_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_winmanboo_space_im_core_codec_protocol_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nfim-server/im-server-api/src/main/java/" +
      "com/winmanboo/space/im/server/api/protoc" +
      "ol/message/message.proto\022*com.winmanboo." +
      "space.im.core.codec.protocol\"\215\001\n\007Message" +
      "\022B\n\006header\030\001 \001(\01322.com.winmanboo.space.i" +
      "m.core.codec.protocol.Header\022>\n\004body\030\002 \001" +
      "(\01320.com.winmanboo.space.im.core.codec.p" +
      "rotocol.Body\"s\n\006Header\022\r\n\005magic\030\001 \001(\005\022\r\n" +
      "\005cmdId\030\002 \001(\005\022\022\n\nbodyLength\030\003 \001(\005\022\017\n\007vers" +
      "ion\030\004 \001(\005\022\022\n\nobjectType\030\005 \001(\005\022\022\n\nclientT" +
      "ype\030\006 \001(\005\"p\n\004Body\022\016\n\006userId\030\001 \001(\t\022\r\n\005app" +
      "Id\030\002 \001(\005\022\014\n\004toId\030\003 \001(\t\022\r\n\005msgId\030\004 \001(\t\022\r\n" +
      "\005cmdId\030\005 \001(\005\022\017\n\007msgType\030\006 \001(\005\022\014\n\004data\030\007 " +
      "\001(\014BD\n2com.winmanboo.space.im.server.api" +
      ".protocol.messageB\014MessageProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_winmanboo_space_im_core_codec_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_winmanboo_space_im_core_codec_protocol_Message_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_com_winmanboo_space_im_core_codec_protocol_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_winmanboo_space_im_core_codec_protocol_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_winmanboo_space_im_core_codec_protocol_Header_descriptor,
        new java.lang.String[] { "Magic", "CmdId", "BodyLength", "Version", "ObjectType", "ClientType", });
    internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_winmanboo_space_im_core_codec_protocol_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_winmanboo_space_im_core_codec_protocol_Body_descriptor,
        new java.lang.String[] { "UserId", "AppId", "ToId", "MsgId", "CmdId", "MsgType", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
