#spring:
#  data:
#    redis:
#      port: 6379
#      host: localhost
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 50
#          max-idle: 20
#      password: wzm123
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#  registry:
#    address: nacos://localhost:8848
#    username: nacos
#    password: nacos
#  protocol:
#    name: dubbo
#    port: 9001
#
#space:
#  im:
#    websocket:
#      port: 8085
#  id:
#    worker-id: 0
#    base-time: 1722484800000
#    seq-bit-length: 10
#  mq:
#    name-server: localhost:9876
#    producer:
#      enable: true
#      group: ${spring.application.name}
#      send-msg-timeout: 3000
#      retry-times-when-send-failed: 2
#      retry-times-when-send-async-failed: 2
#      retry-another-broker-when-not-store-ok: true
#    consumer:
#      enable: true
#      group: ${spring.application.name}
#      consume-from-where: consume_from_first_offset
